version: "3.9"

services:
  redis:
    image: "redis:alpine"
    hostname: redis
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - backnet
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    image: crackaf/tersecode_backend
    working_dir: /backend
    command: >
       sh -c "find . && pwd && 
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - backnet
      - frontnet
  celery:
    build: 
      context: backend
      dockerfile: Dockerfile
    image: crackaf/tersecode_backend
    working_dir: /backend
    command: >
       bash -c "find . && pwd && 
       celery -A tersecode worker -l info"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  frontend:
      build :  
        context: frontend
        dockerfile: Dockerfile
      image: crackaf/tersecode_frontend
      working_dir: /frontend/frontend
      command: bash -c "find . && pwd && npm run serve"
      ports:
          - "80:3000"
      env_file:
        - ./.env
      networks:
        - frontnet
      depends_on:
        - backend


volumes:
  db-data:

networks:
  backnet:
  frontnet:
